version: "3"
services:
    web:
        build: .
        container_name: django_ctn
        restart: "no"
        command: bash -c "
            python3 manage.py collectstatic --no-input &&
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            gunicorn config.wsgi:application -b 0:8000"      
        volumes:
            - ./src:/src
        networks:
            - custom_network

    nginx:
        image: nginx:1.17.10
        container_name: nginx_ctn
        restart: "no"
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./src/static:/src/static_root  
        depends_on:
            - web
        networks:
            - custom_network

    rabbitmq:
      image: 'rabbitmq:3-management'
      container_name: rabbitmq_ctn
      ports:
        # The standard AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
      volumes:
        - ./src:/src

networks:
    custom_network:
        driver: bridge


